
kind: pipeline
type: docker
name: default

steps:
  - name: frontend
    image: node:slim
    commands:
      - yarn config set registry https://registry.npm.taobao.org/
      - yarn
      - yarn run build
  - name: docker
    image: docker
    volumes:
    - name: dockersock
      path: /var/run/docker.sock
    commands:
    - docker build -t kkkkh/blog:dev .
    - docker stop blog
    - docker rm blog
    - docker run -d -p 8080:80 --name blog --restart=always kkkkh/blog:dev
    # - name: docker
    #   image: plugins/docker
    #   settings:
    #     dockerfile: ./Dockerfile
    #     repo: kkkkh/blog
    #     # build_args:
    #     #   - -t kkkkh/blog
    #     tags:
    #       - master
    #     dry_run: true
    #     purge: false
    #     no_cache: false
volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
  
trigger:
  branch:
    - dev
  event:
    - push

