name: Node.js build CI

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      
    - name: Install yarn
      run: npm install -g yarn
      
    - name: Build
      run: yarn install && yarn run build
      
    - name: Deploy
      uses: solybum/hexo-deploy@master
      env:
        PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_REPOSITORY: kkkkh/gen
        BRANCH: gh-pages  
        PUBLISH_DIR: ./dist
