name: Node.js build CI

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      
    - name: Install yarn
      run: npm install -g yarn
      
    - name: Build
      run: | 
        yarn install
        yarn run build 
        cp  dist/index.html dist/404.html
      
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        # 为了让 GitHub触发重新构建页面，您必须使用存储库提供的GitHub令牌来提供操作, GITHUB_TOKEN 是系统默认提供的  不需要单独配置环境变量
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist


